name: CapitalGrille
options:
  bundleIdPrefix: com.jaredgantt
  deploymentTarget:
    iOS: 16.0
settings:
  base:
    SWIFT_VERSION: 5.0
targets:
  CapitalGrille:
    type: application
    platform: iOS
    sources:
      - path: CapitalGrilleApp
    info:
      path: CapitalGrilleApp/Info.plist
      properties:
        CFBundleDisplayName: Capital Grille
        UIStatusBarStyle: UIStatusBarStyleDarkContent
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSAppTransportSecurity:
          NSExceptionDomains:
            "100.106.101.57":
              NSExceptionAllowsInsecureHTTPLoads: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jaredgantt.CapitalGrille
        PRODUCT_NAME: CapitalGrille
        TARGETED_DEVICE_FAMILY: "1,2"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
